name: Generate and push Documentation

on:
  push:
    branches: [ "main", "manual" ]
  pull_request:
    branches: [ "main", "manual"  ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  generate_doc:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
    - name: Checkout code.
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5
      
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate_doc
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
